### ISSUE TITLE
Add Services Advisor Name to App Title (request was just to remove UNHCR - not Services Advisor)

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#102]
@amyngai  - it occurred to me tonight that we don't have the name of the app anywhere prominent. prob too late for a tuesday launch, but wondered what your thoughts are on how we might do this.

**Comment by Edouard-Legoupil** [comment]
Then maybe the question of a kind of logo could be raised... an idea: https://thenounproject.com/term/golf-course/79160/

**Comment by Edouard-Legoupil** [comment]
could also add an icon .ico

**Comment by amyngai** [comment]
I had thought of this in the top left corner but didn't put it in the design. It's probably a bit late now yes..  It was designed to be very utilitarian – with users already knowing what the app is for, so very little was put into the branding of the app :/

flag on golf course is fine :P . Perhaps even something from the Humanitarian font?

**Comment by PeaceGeeks** [comment]
Yes Humanitarian font would be good. Perhaps for SA 1.1

**Comment by PeaceGeeks** [comment]
I am going to open a separate ticket for the logo, because I don't think that is needed for the initial release, but the name DOES need to be in the app for initial release. @amyngai - also, what about having something like 'powered by peacegeeks' in a footer?

**Comment by amyngai** [comment]
`Powered by PeaceGeeks` for sure. 
You can add it as a low priority issue with an `enhancement` label :)

**Comment by Edouard-Legoupil** [comment]
Let's just make sure, that's it's "Services Advisor" and not "UNHCR Services Advisor"
