### ISSUE TITLE
Arabic text is tiny

### ISSUE THREAD

**Issue by cynthialee** [PeaceGeeksSociety/services-advisor#105]
Examples:
![image](https://cloud.githubusercontent.com/assets/3262577/8514455/dbdc4f22-2344-11e5-98af-6631a4c21334.png)

![image](https://cloud.githubusercontent.com/assets/3262577/8514460/fb8ff936-2344-11e5-8945-ecf885ee5698.png)

@PeaceGeeks @amyngai Please comment.

@tuckerbuchy @lkysow @Jareechang

**Comment by amyngai** [comment]
agreed. 

Is there a way to change all fonts when it's switched to arabic? (like... 2 pt bigger. or .em or .rem if you're using them)

**Comment by cynthialee** [comment]
That's something to explore. But on mobile it doesn't look too bad. @PeaceGeeks, can you comment on the size of the Arabic content from what you've seen?

**Comment by cynthialee** [comment]
![screenshot_2015-07-07-17-54-33](https://cloud.githubusercontent.com/assets/3262577/8560875/c7daff94-24d1-11e5-9861-77a326706280.png)

**Comment by PeaceGeeks** [comment]
this looks good on mobile to me.

**Comment by cynthialee** [comment]
In that case, should we keep this issue open? It looks small on the
desktop, but fine on mobile. If only English users access the desktop, we
might downgrade this to low or close it.

**Comment by amyngai** [comment]
sounds good. Let's touch on this again when we're further into QA. 

Probably more important to have the items right aligned https://github.com/PeaceGeeksSociety/services-advisor/issues/98

**Comment by PeaceGeeks** [comment]
I think we do need to fix the desktop version in time for launch - increase the Arabic font by a couple of points.

**Comment by lkysow** [comment]
Fixed in #143
