### ISSUE TITLE
Show/ Hide Map does not display map properly

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#114]
![img_3677](https://cloud.githubusercontent.com/assets/2263033/8538277/0c1f00b4-241f-11e5-81a7-425ace3a49fa.jpg)

**Comment by cynthialee** [comment]
@PeaceGeeks can you try clearing your browser settings, or go in a private mode (sorry, I don't know how in Safari)? It works for me, so your phone might just have an old copy of the website content. Also see if the others have the same problem.

**Comment by PeaceGeeks** [comment]
I did clear my browser history and still had the same problem, and was able to replicate this on another testing device.

**Comment by PeaceGeeks** [comment]
ok this seems to now be resolved since luke redeployed. there is another issue with the display of logos/ buttons that I will open separately.
