### ISSUE TITLE
Make 'Hours' and 'Activities' full width on mobile 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#115]
![img_3678](https://cloud.githubusercontent.com/assets/2263033/8538466/4c42c110-2421-11e5-93a8-5ffa2d3e1ba4.jpg)

column option/ compression means long description/ inefficient use of space

**Comment by cynthialee** [comment]
@PeaceGeeks is this really high? It's not feature or data impacting, so I would recommend a low.

**Comment by PeaceGeeks** [comment]
i'll make it medium. would ideally be nice to have this sorted before launch, but i agree it can be launched without this being fixed.

**Comment by cynthialee** [comment]
Let's merge this one with the display service content one, ok?

**Comment by cynthialee** [comment]
Closing this ticket, will use #116 instead.
