### ISSUE TITLE
What is with the 'Google' icons on all the orgs? 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#117]
![screen shot 2015-07-06 at 9 09 41 pm](https://cloud.githubusercontent.com/assets/2263033/8538585/752184ca-2423-11e5-8a85-d35b28f40f9e.png)

**Comment by PeaceGeeks** [comment]
Google still appears for logos without a logo - another ticket has been created requesting to remove those.

**Comment by arvandtiv** [comment]
the fix above is not related to this issue ... It's fix for https://github.com/PeaceGeeksSociety/servicesadvisor-3.0/issues/117
