### ISSUE TITLE
Word 'Women' (in English) is showing in Women Safe Spaces category on the Arabic site

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#130]
See - http://dev.pgunhcr.peacegeeks.org/#/results?category=Women%20%D9%85%D8%B3%D8%A7%D8%AD%D8%A7%D8%AA%20%D8%A2%D9%85%D9%86%D8%A9 
![screen shot 2015-07-08 at 5 37 38 pm](https://cloud.githubusercontent.com/assets/2263033/8585559/41fabdb6-2598-11e5-893a-5ac300749d4d.png)

**Comment by PeaceGeeks** [comment]
Other odd English words too:

(In pop-up) Show Details, Referral Method

Unknown

**Comment by lkysow** [comment]
This is coming directly from the translation data in `data.csv` so I think we'll need to add the translation for women and then regenerate the `compiled_AR.json` file
