### ISSUE TITLE
Some Arabic label have words reversed (LTR is RTL for multi-worded labels)

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#131]
It looks like when Gmail sends you and I emails with Magdi's translations that it reverses the order of arabic words for the labels (so RTL instead of LTR for multi-worded labels. This seems to also be an issue for the Governorate labels and anything that he has translated. He sends it correctly and then Google does its thing. He was going to send you images of what it should look like. Would that be helpful?

**Comment by lkysow** [comment]
The regions have been fixed

**Comment by lkysow** [comment]
@PeaceGeeks would it be possible for Magdi to tell us which ones are wrong?

**Comment by PeaceGeeks** [comment]
for sure -

**Comment by MagdiRizkallah** [comment]
Here is a start...  May be we can have an interactive meeting to complete that since I do not know where every translation is..
![servicesadvisortranslations](https://cloud.githubusercontent.com/assets/5035201/8938372/257c9aee-3513-11e5-8f81-1282aaf3d0e5.jpg)

**Comment by lkysow** [comment]
@MagdiRizkallah thanks, this is great information. The only other translations are
- in the `filter your search` bar (just click it)
- when you click on an actual service the details will show on the right. Please look at the headings to ensure they're correct.

So if you look at those places then you will have seen everything.

**Comment by lkysow** [comment]
@PeaceGeeks @MagdiRizkallah I can't really do anything with the screenshots, I need to be able to cut and paste.

Please fill out this spreadsheet with any of the incorrect translations (e.g. the regions): https://docs.google.com/spreadsheets/d/1pJUGN9PfuUd7bCMSiNPc6aZ7IxGs5mUng4_LJ_dPtbw/edit?usp=sharing

I haven't had any issues cutting and pasting from the spreadsheet so if it's the correct direction in the spreadsheet then it will be the correct direction when it's in the website.

**Comment by MagdiRizkallah** [comment]
Done both category levels  and the regions to the best of my ability.

**Comment by PeaceGeeks** [comment]
@alsamhou - can you QA Magdi's translations before Luke goes ahead and puts them in please?

**Comment by alsamhou** [comment]
Translation is fine by me ! i did small update in RED.

**Comment by lkysow** [comment]
I've added the new translations to the app. Ensure you do a hard refresh to see the changes. If it looks good please close this ticket.

**Comment by PeaceGeeks** [comment]
@alsamhou - back to you for full site QA please!

**Comment by alsamhou** [comment]
overall looks good. but some are swapped like in this image: 
![untitled](https://cloud.githubusercontent.com/assets/12682965/9192690/ec1952ac-4015-11e5-825d-5f8c28312f5e.png)

**Comment by lkysow** [comment]
That is an unfortunate result of how the service data is being translated. For the service data we have a big translation csv file that we just do a search and replace with. Can you paste the actual text that is incorrect here please so I can find which words are wrong?

**Comment by MagdiRizkallah** [comment]
@lkysow Added the column of existing Arabic to the doc...

@alsamhou you need to put all errors you find with the correction in the doc https://docs.google.com/spreadsheets/d/1pJUGN9PfuUd7bCMSiNPc6aZ7IxGs5mUng4_LJ_dPtbw/edit?usp=sharing

**Comment by mackh** [comment]
I believe this has been completed

**Comment by PeaceGeeks** [comment]
@MagdiRizkallah - can you QA?

**Comment by PeaceGeeksProjects** [comment]
Verified
