### ISSUE TITLE
Misc Arabic translation issues

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#136]
Women (see #130)
Open at
Activity Details (In pop-up) 
Show Details (In pop-up) 
Referral Method, (In pop-up) 
Unknown

**Comment by PeaceGeeks** [comment]
Also word reversal

**Comment by MagdiRizkallah** [comment]
أماكن آمنة للنساء = Women Spaces Safe
مجهول = Unknown
نفتتح الساعة = Open at
