### ISSUE TITLE
Map filters reset after a post location is clicked and closed

### ISSUE THREAD

**Issue by amyngai** [PeaceGeeksSociety/services-advisor#138]
notes in the gif
- clicking the "x" keeps the filters (first click)
- clicking on the map resets the filters? it might be because it's filtering on a region.. 
  ![map filter reset](https://cloud.githubusercontent.com/assets/5739342/8629253/6bb3962e-270e-11e5-9327-3de8c341ee23.gif)

expected behaviour
- when a modal is open, clicking off it should be treated like a "x"
- if the map is clicked while a filter is on, the filter should be an `and` not `or`
- we should also probably add what it's filtered on after `Search Result`

**Comment by lkysow** [comment]
We should just kill clicking on a region to filter then. Keeping track of which state we're in an whether clicking on a region to filter is okay is too much work.

**Comment by amyngai** [comment]
good suggestions ^

**Comment by lkysow** [comment]
I've removed filtering on region via clicking.
