### ISSUE TITLE
When user switches multiple times between language versions, the number of records changes

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#142]
I started in Arabic, switched to English, and then back to Arabic. The total number of records in the first two instance is 75. The third switch, it is 150. When I tried to filter on this, it reset back to 75, so this is an issue, but low priority.

![screen shot 2015-07-21 at 11 26 08 am](https://cloud.githubusercontent.com/assets/2263033/8803112/5a617f9a-2f9b-11e5-9009-9a10ea884a5d.png)

**Comment by PeaceGeeks** [comment]
![screen shot 2015-07-21 at 11 37 44 am](https://cloud.githubusercontent.com/assets/2263033/8803402/135a6a42-2f9d-11e5-8400-ba1043dfb681.png)

**Comment by lkysow** [comment]
Should be fixed now.
