### ISSUE TITLE
Language selector overlaps with white space in header

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#147]
![img_3699](https://cloud.githubusercontent.com/assets/2263033/8819712/f78abc4e-3024-11e5-953d-b27b7d320d51.PNG)

**Comment by lkysow** [comment]
![image](https://cloud.githubusercontent.com/assets/1034429/9152709/e3d6b844-3de7-11e5-965d-a36d9ffa88b3.png)
