### ISSUE TITLE
On mobile, I click on service record but map marker does not display on map

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#154]
![screen shot 2015-07-27 at 11 17 42 pm](https://cloud.githubusercontent.com/assets/2263033/8924786/272276b4-34b6-11e5-82e4-d5e8a95204d0.png)

**Comment by lkysow** [comment]
@PeaceGeeks are you sure it's not showing or is it just not showing in the part of the map you can see? I think it's the latter.

**Comment by lkysow** [comment]
Would be nice to center the map on the location, but maybe the easiest thing we can do now is to just zoom out the map when clicking on a record from the list?

**Comment by PeaceGeeks** [comment]
Yes sure - I zoomed out to the full country. It is not showing at all. Also, half the map was cut off - related to another mobile bug that I logged a couple of weeks ago where the bottom half of the map did not display.

**Comment by lkysow** [comment]
Are you on your mobile phone or using the browser on your desktop with a
small window?

Which marker is it? We'll need the id in the url.

**Comment by PeaceGeeks** [comment]
mobile, but I think i replicated on a small desktop window too. Let me try to reproduce just now.

**Comment by PeaceGeeks** [comment]
dev seems to be down - any idea why?

**Comment by PeaceGeeks** [comment]
Ok so this is the sequence of events - I can't reproduce it consistently
1 I filter on Cash
2 I choose financial assistance
3 I click on the second option for IRC (Ar-Ramtha City: Financial Assistance)

Problem #1: The record does not align to the top, but instead to a random midway point in the record where the user can't see the 'Back' or 'Show/ Hide Map' button

Problem #2: When I scroll to the top and click on 'Show/ Hide Map' the map does not fully display (so I don't know if the icon is displaying) I try to zoom in or out, but that just makes it worse. 

![img_3730](https://cloud.githubusercontent.com/assets/2263033/9101869/0d8e3fb6-3ba1-11e5-8633-1e2aa9b57c73.PNG)
![img_3729](https://cloud.githubusercontent.com/assets/2263033/9101870/0d8ebe6e-3ba1-11e5-917e-ce8418eceeba.PNG)

**Comment by lkysow** [comment]
This has been fixed.
