### ISSUE TITLE
Some records do not display all record fields

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#160]
I filter on 'Referral not required' and get 3 records
I click thru to the first map marker and click 'Show Details'
Not all fields for that record display

ALSO
I click on the map record for the next record but the map record in the right window does not change, which I expected it to do. 

I recommend either that: 
1. this behaviour change so that the right window displays the record data for the corresponding map marker; (prederred)
AND/ OR
2. the 'Show Details' link should appear at the bottom of the preview box. It is not intuitive that the user would click there to get the right window data to change.

**Comment by lkysow** [comment]
1. There's no data for that record if it's not being shown
2. The sidebar not updating is is logged in #66

**Comment by lkysow** [comment]
@PeaceGeeks I think this should be closed. The first issue is the data from activity info and the second has been fixed.

**Comment by PeaceGeeks** [comment]
Hi @lkysow - question for you. For 'Referral Method', when it displays as 'unknown', it that an actual value, or is that what displays when there is no value? If it is the former, please close. If it is the latter, then I wonder why this field doesn't display for the records above. Any thoughts?

**Comment by lkysow** [comment]
@PeaceGeeks that's what it displays when there's no data. I don't know why it doesn't have data, this is what we got from syrianrefugeeresponse.org:

``` json
{
  "type": "Feature",
  "id": 805083957,
  "properties": {
    "locationName": "Irbid City",
    "partnerName": "IRC",
    "activity": 5602,
    "activityCategory": "PROTECTION",
    "activityName": "Psychosocial & Mental Health",
    "startDate": "2012-11-02",
    "endDate": "2016-09-01",
    "indicators": {

    },
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      35.85,
      32.55556
    ]
  }
}
```

**Comment by lkysow** [comment]
@PeaceGeeks what are we doing with this ticket?

**Comment by PeaceGeeks** [comment]
Closing
