### ISSUE TITLE
Add Service Provider Address and Hotline number to service provider records

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#163]
These are the AI fields

![image001](https://cloud.githubusercontent.com/assets/2263033/9080108/7af7c802-3b05-11e5-87dc-7996086df313.png)

**Comment by lkysow** [comment]
As you say, right now that data isn't coming from the syrianrefugeeresponse.org: https://www.syrianrefugeeresponse.org/resources/sites/points?activity=5574

Example:

``` json
{
  "type": "Feature",
  "id": 82959961,
  "properties": {
    "locationName": "Ajlun Governorate",
    "partnerName": "IOCC",
    "comments": "\nFadi Wakileh\nfwakileh@iocc.org\n79 022 05 90\nfwakileh@iocc.org",
    "activity": 5579,
    "activityCategory": "FOOD",
    "activityName": "Food Security",
    "startDate": "2014-01-01",
    "endDate": "2014-12-31",
    "indicators": {
      "Distribution of food parcels": 1
    },
    "5. Coverage": {
      "North": true
    },
    "6. Availability": {
      "Bimonthly": true
    },
    "7. Availability Day": {
      "Sun-Thurs": true
    },
    "8. Office Open at": {
      "8:30am": true
    },
    "9. Office close at": {
      "Close at 17:00pm": true
    },
    "13. Feedback Mechanism": {
      "Excel Tracking table": true
    },
    "1. Registration Type Requirement": {
      "Valid UNHCR ASC and MOI card": true
    },
    "2. Nationality": {
      "No restriction": true
    },
    "3. Intake Criteria": {
      "Open to all": true
    },
    "Referral required": "referral-not-required"
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      35.71104,
      32.2968
    ]
  }
}
```

**Comment by alsamhou** [comment]
Who should update the script to fetch this information? I don't understand the missing side?

**Comment by PeaceGeeks** [comment]
Hi Murad, 
Luke was pointing out that the fields are not coming from Activity Info, but instead from https://www.syrianrefugeeresponse.org. Is there an equivalent field on Activity Info that could be used?

Otherwise, I will talk to Mack about this tomorrow (see my email from last about this matter). Also, have you been asking service providers to start including this data yet?

**Comment by lkysow** [comment]
Update: these fields are coming through but they don't contain any address information, so we're not displaying them.

**Comment by PeaceGeeks** [comment]
@lkysow, @alsamhou and i discussed this - they will start populating this for the next fiscal year the current one is coming to a close so they feel it doesn't make sense to do this now. @alsamhou - can you confirm when the next fiscal year starts?

**Comment by alsamhou** [comment]
we are working on creating 2016 database in activity info. we should launche it next week 7th/Oct.
