### ISSUE TITLE
Pills not deleting consistently on clicking the x

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#182]
the issues with not being able to delete the pills seems to be back again - inconsistent but definitely back

amy got that as well. 
Steps to reproduce for her:
- add filter pills
- leave page
- come back
- pills can’t be deleted

**Comment by Jareechang** [comment]
hi guys, I was testing this briefly on local but it seems to be working for me ? 
has this issue been fixed or something?

**Comment by lkysow** [comment]
No, I think it's just hard to reproduce. Maybe look at the logic to see if
there's anything amiss.

**Comment by lkysow** [comment]
Fixed!
