### ISSUE TITLE
Update Filters UI

### ISSUE THREAD

**Issue by amyngai** [PeaceGeeksSociety/services-advisor#195]
TODO
- ~~mockups up shortly~~ (done, look below)

Idea:
- I don't like the modal. It's inconsistent in web not the best experience in mobile. 
- Going to redesign it as a panel instead of a modal

**Comment by amyngai** [comment]
![desktop filters](https://cloud.githubusercontent.com/assets/5739342/11454686/e156be60-95ea-11e5-8b66-da4ee010d2be.png)
![desktop filters web](https://cloud.githubusercontent.com/assets/5739342/11454687/e1583088-95ea-11e5-952e-7e5341f8f4cd.png)
<img src="https://cloud.githubusercontent.com/assets/5739342/11454685/e1561de8-95ea-11e5-9021-b7d205667c43.png" width="350px">

**Comment by lkysow** [comment]
Nice work guys!
