### ISSUE TITLE
Style for search list headers

### ISSUE THREAD

**Issue by amyngai** [PeaceGeeksSociety/services-advisor#34]
Just noticed that the list headers need some differentiation. Can we change the colour to `#E7EDF1`

![screen shot 2015-04-27 at 6 17 50 pm](https://cloud.githubusercontent.com/assets/5739342/7361230/f9c677fe-ed09-11e4-8943-02e228689253.png)

**Comment by lkysow** [comment]
Yep!

--Luke

**Comment by lkysow** [comment]
@cynthialee made these dropdowns now so we should close this
