### ISSUE TITLE
Build routes and views

### ISSUE THREAD

**Issue by lkysow** [PeaceGeeksSociety/services-advisor#5]
Following the wires here, build out the separate views in Angular. Then add the buttons that let you go in between views.

Desktop: https://marvelapp.com/a3fa40
Mobile: https://marvelapp.com/625111

**Comment by amoghsa** [comment]
so are we using search branch for angular app?

**Comment by lkysow** [comment]
yep!

**Comment by lkysow** [comment]
Done!
