### ISSUE TITLE
redesign UI so it’s just a space, not a text entry

### ISSUE THREAD

**Issue by amyngai** [PeaceGeeksSociety/services-advisor#58]

**Comment by cynthialee** [comment]
@amyngai I think we need to define the space. It looks a little funny with just the filter button floating by itself. 

Nothing selected:
![image](https://cloud.githubusercontent.com/assets/3262577/7977264/ad43a9fa-0a3d-11e5-8da9-b796f245c9cf.png)

Something selected:
![image](https://cloud.githubusercontent.com/assets/3262577/7977260/8ed0a8e2-0a3d-11e5-97b1-ead73905fa3e.png)

Also, do you have any thoughts on what a hovered button should look like?

**Comment by amyngai** [comment]
good question. 

Filter button: 
- pull it closer to the left (anchor with the top left corner)
- Replace the name `Filter your search` (this is probably the more obvious copy)
- Change shape to simply the following pill tags

Pill Tags
- 5 px border radius. 
- use the humanitarianfont/fontawesome "close" font for the `x`
- Use regular sentence case instead of uppercase

Hover states
- refer to image
- hover black text, click back to white text

![screen shot 2015-06-03 at 11 25 12 pm](https://cloud.githubusercontent.com/assets/5739342/7978226/d44d17a2-0a47-11e5-83dc-0551ce56040a.png)

![screen shot 2015-06-03 at 11 20 29 pm](https://cloud.githubusercontent.com/assets/5739342/7978192/9af84710-0a47-11e5-88a0-e8d1baa6b87f.png)

thoughts?

**Comment by cynthialee** [comment]
@amyngai The shapely filter is a bit beyond me atm. Also, how do you see this for mobile?

**Comment by amyngai** [comment]
little bit like this. 
![pinterest tags](https://cloud.githubusercontent.com/assets/5739342/8051448/41af8cd4-0e31-11e5-8245-cf8f3ff3f9af.gif)

thoughts?

![screen shot 2015-06-08 at 10 57 52 pm](https://cloud.githubusercontent.com/assets/5739342/8051499/e1bb1b76-0e31-11e5-847d-3f3cebdc8b8b.png)

**Comment by cynthialee** [comment]
That's a bit complicated for me to do with all the other visuals. What
about a placeholder "filter your search" and selecting the options?
Example: see multiple select boxes section.

https://select2.github.io/examples.html

Thoughts?

Cynthia

**Comment by amyngai** [comment]
Good find! The multiple select boxes seems perfect.

I'm good with "filter your search" placeholder. Let me know if you need further styling when you've implemented it.

**Comment by tuckerbuchy** [comment]
What's going on with the ticket at the moment? Could i start on the ticket to make the filters show up as pills?

**Comment by cynthialee** [comment]
Sorry Tucker. I'm working on this...I'll try to finish this tonight so you
can work on the pills.

Cynthia
