### ISSUE TITLE
filters show up in search bar as a pill

### ISSUE THREAD

**Issue by amyngai** [PeaceGeeksSociety/services-advisor#61]

**Comment by tuckerbuchy** [comment]
Making some progress on this one.

**Comment by tuckerbuchy** [comment]
PR opened https://github.com/PeaceGeeksSociety/services-advisor/pull/97

**Comment by PeaceGeeks** [comment]
@amyngai - what is the expected behaviour here?

**Comment by amyngai** [comment]
it's what's written in the title.

i believe it's already done.
