### ISSUE TITLE
when you click on a map icon it automatically shows the detail view in the sidebar

### ISSUE THREAD

**Issue by amyngai** [PeaceGeeksSociety/services-advisor#66]

**Comment by PeaceGeeks** [comment]
@amyngai - what is the expected behaviour?

**Comment by lkysow** [comment]
Right now it doesn't automatically show the detail view, it brings up a pop-up and then you can click on show details. I agree that this is low priority.

**Comment by amyngai** [comment]
hm. can't remember. I think it was just part of the list of issues that we wrote a while ago. 

I think the issue is that it _should_ show the detail view when a map icon is clicked. It should be a 1 step process instead of `click icon`> `open pop-up` > `click to show detail`. the last 2 steps should happen together after the 1 step

**Comment by lkysow** [comment]
This works now.
