### ISSUE TITLE
Sprite Images

### ISSUE THREAD

**Issue by amyngai** [PeaceGeeksSociety/services-advisor#71]

**Comment by amyngai** [comment]
add sprite images to list of services
![unhcr_jordan_-_service_advisor](https://cloud.githubusercontent.com/assets/5739342/8756191/51ce52a4-2c85-11e5-868e-9d3440bc7c03.jpg)

**Comment by lkysow** [comment]
Duplicated by #73 where we're using an icon font so no spriting.
