### ISSUE TITLE
star icons on categories need to have images

### ISSUE THREAD

**Issue by amyngai** [PeaceGeeksSociety/services-advisor#73]

**Comment by tuckerbuchy** [comment]
Unsure of what this ticket is referring too... could I get some clarification?

**Comment by PeaceGeeks** [comment]
See Screenshot - service sub-category (UNHCR category) - Financial Assistance in this example. 

![screen shot 2015-06-17 at 10 58 42 pm](https://cloud.githubusercontent.com/assets/2263033/8225040/89e36830-1544-11e5-9f54-0ba49d247608.png)

**Comment by tuckerbuchy** [comment]
Right but what do you mean, should the icons be changed to images?

**Comment by PeaceGeeks** [comment]
See current app - http://data.unhcr.org/jordan/services-advisor/

Each service type has a dedicated icon

**Comment by lkysow** [comment]
Got this working for English, have to do it for arabic by translating the category back to the original english

**Comment by lkysow** [comment]
The current arabic site doesn't have this: http://data.unhcr.org/jordan/services-advisor/index_AR.html#map-filters doesn't have this

![image](https://cloud.githubusercontent.com/assets/1034429/8924724/5423c77c-34b5-11e5-81cf-54458fc6f1db.png)

**Comment by lkysow** [comment]
But now we do!
