### ISSUE TITLE
down arrow should point to the right and then point down when you expand the category

### ISSUE THREAD

**Issue by amyngai** [PeaceGeeksSociety/services-advisor#74]

**Comment by amoghsa** [comment]
Just to get started (get familiarized with recent changes), I fixed this one.. :smile: Please check changes. 

https://github.com/amoghsa/services-advisor/commit/b26698d101917e99bdb34dd48f37844f29b0a81f

@cynthialee @lkysow

**Comment by lkysow** [comment]
@amoghsa awesome, super slick!
