### ISSUE TITLE
Filter options are not displaying in 2 columns

### ISSUE THREAD

**Issue by cynthialee** [PeaceGeeksSociety/services-advisor#80]
When I click "Filter Your Search", the filter options, i.e. organizations, should appear in 2 columns. 

![image](https://cloud.githubusercontent.com/assets/3262577/8051148/b4c065bc-0e2d-11e5-8290-901614552018.png)

**Comment by cynthialee** [comment]
@Jareechang Hey Jerry, is this just something on my local?

**Comment by Jareechang** [comment]
@cynthialee hmmm I will look into that one
