### ISSUE TITLE
Filter - Make the whole box clickable

### ISSUE THREAD

**Issue by amyngai** [PeaceGeeksSociety/services-advisor#86]
usability improvement. 

Currently, only clicking the checkbox will check the item. Can we make the whole box clickable to improve usability for inputs? This will significantly improve the mobile experience.

![unhcr_services_advisor](https://cloud.githubusercontent.com/assets/5739342/8164434/ea62e6c6-133d-11e5-83d1-b7fc22a8ce39.jpg)

**Comment by lkysow** [comment]
Done.
