### ISSUE TITLE
Darken the secondary colour

### ISSUE THREAD

**Issue by amyngai** [PeaceGeeksSociety/services-advisor#87]
Currently:
body background: white
secondary: #F8FAFB

<img src="https://cloud.githubusercontent.com/assets/5739342/8164767/3606cd5c-1340-11e5-9d5e-b9616d0834b6.png" width="400px">

Designed:
body background: #F8FAFB
Secondary: #E9EDEF

<img src="https://cloud.githubusercontent.com/assets/5739342/8164771/3a7258c0-1340-11e5-9461-0583c6ad47b4.png" width="400px">

**Comment by PeaceGeeks** [comment]
@amyngai - this was done on Tuesday, correct?
