### ISSUE TITLE
Prefilter on "End Date"

### ISSUE THREAD

**Issue by Edouard-Legoupil** [PeaceGeeksSociety/services-advisor#88]
The geojson file includes an "End Date" property for each services. 

We may need to add a pre-filter that will show only services who end date is after "current date"

**Comment by PeaceGeeks** [comment]
hi @tuckerbuchy - was talking with edouard this morning and we feel that this ticket should be part of the release. can you take a look? there are many services that are expired (i.e. offices that are now closed) and we do not want to include these offices in the lists. thanks!
