### ISSUE TITLE
way for users to switch between English and Arabic version of app

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#92]
currently there is no way to go from the English version to the Arabic version in the app leading to some to believe that there is no other language version.

**Comment by amyngai** [comment]
The guys have put in this switcher in the top right corner of the app

![_translate__unhcr_services_advisor](https://cloud.githubusercontent.com/assets/5739342/8235644/e25ae24c-1597-11e5-9769-15d7d1010afc.jpg)

**Comment by PeaceGeeks** [comment]
HI @amyngai - thanks - yes i remember seeing tickets about this that I thought had been closed, but that I now can't find, but I am not see that box in dev. Is it still on someone's local?

**Comment by amyngai** [comment]
I'm looking at the `Search` branch. But might be good to clarify with @lkysow . I'm not sure what you're looking at.

**Comment by PeaceGeeks** [comment]
looking here - dev.pgunhcr.peacegeeks.org

**Comment by cynthialee** [comment]
It's in the search branch of this repo @PeaceGeeks. I don't know if it's actually deployed on dev.pgunhcr.peacegeeks.org.

**Comment by lkysow** [comment]
The dev app will have to be redeployed for you to be able to see the
changes on that site. I'll do it when I'm back.

**Comment by PeaceGeeks** [comment]
@lkysow - just pinging about this - can you deploy when you have a chance?

**Comment by lkysow** [comment]
@PeaceGeeks yep, just getting back into the swing of things, I should be able to deploy tonight

**Comment by PeaceGeeks** [comment]
Great!

**Comment by PeaceGeeks** [comment]
looks good! could we theme this so that it is the same height as the boxes/ elements to the left?

**Comment by amyngai** [comment]
we can probably do a simple style:

```
background: #F8FAFB;
position: relative;
width: 60px;
line-height: 1;
border: 0;
height: 35px;
font-weight: bold;
```

we also need to take the 5 px in this class

```
#searchNav #preferences {
top: 5px;  <--- needs to be 0
```

![unhcr_services_advisor_and_backend_screens_employer](https://cloud.githubusercontent.com/assets/5739342/8364953/c6c3574c-1b3e-11e5-8bd0-8ac8122f9a2c.jpg)

**Comment by PeaceGeeks** [comment]
Perfect!!!!

**Comment by amyngai** [comment]
this was just done in browser :P
someone will need to implement it

**Comment by PeaceGeeks** [comment]
yes understood!

**Comment by tuckerbuchy** [comment]
What's the status on this ticket now? I see the drop down, but has the functionality been worked on?

**Comment by PeaceGeeks** [comment]
Hi @tuckerbuchy - the switcher is there, and I think @amyngai created the code to theme it, but I don't believe anyone has put it into the code base.

**Comment by amyngai** [comment]
@tuckerbuchy this is the other issue we have for this: https://github.com/PeaceGeeksSociety/services-advisor/issues/62

seems like @lkysow is assigned to it, perhaps he has more insight. 

renee is correct that I have posted the style above:https://github.com/PeaceGeeksSociety/services-advisor/issues/92#issuecomment-115389510 which also has not been implemented

**Comment by lkysow** [comment]
This functionality is working, we just need to
- get the translations, that will be done soon
- also switch the data to come from `compiled_AR.json`. I can do that.

**Comment by lkysow** [comment]
Unfortunately nothing is as easy as it looks. When `compiled_AR.json` is created, the keys of the json change, so for example 

``` json
"8. Office Open at": {}
```

Becomes

``` json
"8. موعد فتح المكتب": {}
```

A lot of our code has those strings hardcoded so the translated data breaks the app. I looked at the deployed app in Arabic: http://data.unhcr.org/jordan/services-advisor/index_AR.html and they've gone through and changed all the JS to work with the Arabic data.

What I think we should do is add those strings to our translations file and then any time we need to use the string we run it through `$translate` first. This will take more time than previously thought unfortunately.

**Comment by lkysow** [comment]
Remaining:
- when switching to English reload app
- translate regions
- various missing translations
