### ISSUE TITLE
Open on ActivityInfo links don't work - is this just for case workers? 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/services-advisor#94]

**Comment by Edouard-Legoupil** [comment]
Yes, it's just for Case worker -- who indeed have a login for activityInfo

**Comment by Edouard-Legoupil** [comment]
Ideally this link should be displayed only for the "NGO worker" use case. -- see: https://github.com/PeaceGeeksSociety/services-advisor/issues/90
